DROP TABLE IF EXISTS RATE CASCADE;
DROP TABLE IF EXISTS CURRENCY CASCADE;
CREATE TABLE CURRENCY (
  CODE VARCHAR(3) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  PRIMARY KEY (CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE RATE (
  QUOTE DECIMAL(10,6) NOT NULL,
  TIMESTAMP DATETIME NOT NULL,
  TARGET_CODE VARCHAR(3) NOT NULL,
  SOURCE_CODE VARCHAR(3) NOT NULL,
  PRIMARY KEY (SOURCE_CODE,TARGET_CODE),
  FOREIGN KEY (TARGET_CODE) REFERENCES CURRENCY(CODE),
  FOREIGN KEY (SOURCE_CODE) REFERENCES CURRENCY(CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO CURRENCY(CODE, DESCRIPTION) VALUES ('EUR', 'European Euro');
INSERT INTO CURRENCY(CODE, DESCRIPTION) VALUES ('UAH', 'Ukrainian Hryvna');
INSERT INTO CURRENCY(CODE, DESCRIPTION) VALUES ('USD', 'United States Dollar');